apiVersion: apps/v1
kind: Deployment
metadata:
  name: documents-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: documents
  template:
    metadata:
      labels:
        app: documents
    spec:
      containers:
        - name: documents
          image: vijayvaddem/documents
---
apiVersion: v1
kind: Service #ClusterIP service type (default)
metadata:
  name: documents-clusterip-svc
spec:
  selector:
    app: documents #type should go here. Default is ClusterIP
  ports:
    - name: documents
      protocol: TCP
      port: 4000
      targetPort: 4000
