apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-bus
  template:
    metadata:
      labels:
        app: event-bus
    spec:
      containers:
        - name: event-bus
          image: vijayvaddem/event-bus:latest
---
apiVersion: v1
kind: Service #ClusterIP service type (default)
metadata:
  name: event-bus-svc
spec:
  selector:
    app: event-bus #type should go here. Default is ClusterIP
  ports:
    - name: event-bus
      protocol: TCP
      port: 4005
      targetPort: 4005
